
# pass variables necessary for the toolchain (needed for try_compile)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARCH USE_CLANG_CL)

# the name of the target operating system
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

# set the generator platform
if (NOT DEFINED CMAKE_GENERATOR_PLATFORM)
    if(ARCH STREQUAL "amd64")
        set(CMAKE_GENERATOR_PLATFORM "x64")
    elseif(ARCH STREQUAL "arm")
        set(CMAKE_GENERATOR_PLATFORM "ARM")
    elseif(ARCH STREQUAL "arm64")
        set(CMAKE_GENERATOR_PLATFORM "ARM64")
    else()
        set(CMAKE_GENERATOR_PLATFORM "Win32")
    endif()
endif()

if(USE_CLANG_CL)
    if(NOT DEFINED CMAKE_C_COMPILER)
        set(CMAKE_C_COMPILER clang-cl)
    endif()
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER clang-cl)
    endif()

    if(NOT DEFINED CMAKE_LINKER)
        set(CMAKE_LINKER lld-link)
    endif()
    if(NOT DEFINED CMAKE_AR)
        set(CMAKE_AR llvm-lib)
    endif()

    if (ARCH STREQUAL "amd64")
        set(CMAKE_C_COMPILER_TARGET "x86_64-pc-windows-msvc")
        set(CMAKE_CXX_COMPILER_TARGET "x86_64-pc-windows-msvc")
        set(MSVC_C_ARCHITECTURE_ID "x64")
        set(MSVC_CXX_ARCHITECTURE_ID "x64")
    elseif(ARCH STREQUAL "arm")
        set(CMAKE_C_COMPILER_TARGET "arm-pc-windows-msvc")
        set(CMAKE_CXX_COMPILER_TARGET "arm-pc-windows-msvc")
        set(MSVC_C_ARCHITECTURE_ID "ARM")
        set(MSVC_CXX_ARCHITECTURE_ID "ARM")
    elseif(ARCH STREQUAL "arm64")
        set(CMAKE_C_COMPILER_TARGET "arm64-pc-windows-msvc")
        set(CMAKE_CXX_COMPILER_TARGET "arm64-pc-windows-msvc")
        set(MSVC_C_ARCHITECTURE_ID "ARM64")
        set(MSVC_CXX_ARCHITECTURE_ID "ARM64")
    else()
        set(CMAKE_C_COMPILER_TARGET "i686-pc-windows-msvc")
        set(CMAKE_CXX_COMPILER_TARGET "i686-pc-windows-msvc")
        set(MSVC_C_ARCHITECTURE_ID "X86")
        set(MSVC_CXX_ARCHITECTURE_ID "X86")
    endif()

    # Avoid wrapping RC compiler with cmcldeps utility for clang-cl.
    # Otherwise it breaks cross-compilation (32bit ReactOS cannot be compiled by 64bit LLVM),
    # target architecture is not passed properly
    set(CMAKE_NINJA_CMCLDEPS_RC OFF)
else()
    set(CMAKE_C_COMPILER cl)
    set(CMAKE_CXX_COMPILER cl)
endif()

if(NOT DEFINED CMAKE_MC_COMPILER)
    # llvm-mc is the machine code tool, not a MS-compatible message compiler.
    # Once an mc equivalent is available, you may define CMAKE_MC_COMPILER for
    # a non-Microsoft equivalent.
    set(CMAKE_MC_COMPILER mc)
endif()
if(NOT DEFINED CMAKE_RC_COMPILER)
    set(CMAKE_RC_COMPILER llvm-rc)
endif()

if(ARCH STREQUAL "amd64")
    if(NOT DEFINED CMAKE_ASM_MASM_COMPILER)
        set(CMAKE_ASM_MASM_COMPILER ml64)
    endif()
    set(CMAKE_ASM_MASM_FLAGS_INIT "/Cp")
elseif(ARCH STREQUAL "arm")
    if(NOT DEFINED CMAKE_ASM_MASM_COMPILER)
        set(CMAKE_ASM_MASM_COMPILER armasm)
    endif()
elseif(ARCH STREQUAL "arm64")
    if(NOT DEFINED CMAKE_ASM_MASM_COMPILER)
        set(CMAKE_ASM_MASM_COMPILER armasm64)
    endif()
else()
    if(NOT DEFINED CMAKE_ASM_MASM_COMPILER)
        set(CMAKE_ASM_MASM_COMPILER ml)
    endif()
    set(CMAKE_ASM_MASM_FLAGS_INIT "/Cp")
endif()

set(CMAKE_C_STANDARD_LIBRARIES "" CACHE INTERNAL "")

set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/overrides-msvc.cmake")
